global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:5000"]
    metrics_path: /metrics

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:5001"]
    metrics_path: /metrics

  - job_name: "inventory-service"
    static_configs:
      - targets: ["inventory-service:5002"]
    metrics_path: /metrics

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:5003"]
    metrics_path: /metrics
